### ISSUE TITLE
New videos in some channels not loaded

### ISSUE THREAD

**Issue by jk-85** [bitchute-kodi/plugin.video.bitchute#17]
I have problems accessing the latest videos from this channel:
https://www.bitchute.com/channel/der_volkslehrer/

Some other channels are afflicted, too.

And a feature request: It would be nice to have a search function. And the alpha-state, I have to subscribe on my pc, then go to the KODI-PC and access my favorite channels, but I can't see all videos from bitchute, only my own subscribed channels.

Many thanks for this plugin !

**Comment by Zer0C001** [comment]
These don't have magnet links, pull request #18  should solve this.

**Comment by jk-85** [comment]
Thanks very much, it works now !!

**Comment by Zer0C001** [comment]
I think we can close this, since #18 has been merged.
