### ISSUE TITLE
No next page ?

### ISSUE THREAD

**Issue by cw-kid** [bitchute-kodi/plugin.video.bitchute#25]
Hi

I've just installed this add-on, version 1.0.0

I can access my subscribed channels OK, but all of them only show one page worth of videos in Kodi. 

There is no next page button to list the next page of videos?

Running LibreElec Kodi 18.9 Leia.

Thanks

**Comment by jasonfrancis** [comment]
I could not reproduce this.  On multiple systems when I browse either the `Subscription Activity` or or individual channels I'm subscribed to I get a `Next Page` option.
