### ISSUE TITLE
Not currently logged in

### ISSUE THREAD

**Issue by stuartraetaylor** [bitchute-kodi/plugin.video.bitchute#6]
I have installed the plugin on LibreELEC 9.0.1 (Kodi 18.1). However navigating to any of the menu items within the plugin displays a generic error message on screen, and the message 'Not currently logged in' is output to the log file.

What is the recommended way to login to BitChute for the plugin?

The full log output from selecting 'Subscription Activity' from kodi.log is as follows:

```
2019-06-08 13:22:49.462 T:1497572208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Not currently logged in.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.bitchute/main.py", line 686, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.bitchute/main.py", line 666, in router
                                                listSubscriptionVideos(int(params.get('page', '1')))
                                              File "/storage/.kodi/addons/plugin.video.bitchute/main.py", line 505, in listSubscriptionVideos
                                                subs = fetchLoggedIn(baseUrl + "/subscriptions")
                                              File "/storage/.kodi/addons/plugin.video.bitchute/main.py", line 278, in fetchLoggedIn
                                                raise ValueError("Not currently logged in.")
                                            ValueError: Not currently logged in.
                                            -->End of Python script error report<--
2019-06-08 13:22:49.678 T:1505964912   ERROR: GetDirectory - Error getting plugin://plugin.video.bitchute/?action=subscriptionActivity
2019-06-08 13:22:49.680 T:1936954016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bitchute/?action=subscriptionActivity) failed
```

Thanks!

**Comment by jasonfrancis** [comment]
At present the plugin only works if you login to a Bitchute account.  You can enter your Bitchute username and password in the settings for the plugin.  In Kodi you can right-click on the plugin and choose settings.

Hope that helps.

**Comment by stuartraetaylor** [comment]
Okay so it turned out the settings menu was missing from the plugin because the resources directory was empty in the installation (under .kodi/addons/plugin.video.bitchute).

I had installed the plugin by cloning the git repo and then creating a ZIP file and then installing the ZIP file from the Kodi interface, so I'm not sure what caused the installation to fail copying in the resources.

Manually copying the files into the resources directory and restarting Kodi allowed me to input my login details and solved the issue.

Thanks!

**Comment by salfter** [comment]
I have the same error.  I installed it by downloading an archive from GitHub, uploading it to one of my LibreELEC boxes, and selecting "install from zipfile."  I checked under ~/.kodi/addons/plugin.video.bitchute and found everything:

```
.kodi/addons/plugin.video.bitchute/:
.           .gitignore  Readme.md   icon.png    resources
..          LICENSE     addon.xml   main.py

.kodi/addons/plugin.video.bitchute/resources:
.             ..            language      settings.xml

.kodi/addons/plugin.video.bitchute/resources/language:
.        ..       English  Hebrew

.kodi/addons/plugin.video.bitchute/resources/language/English:
.           ..          strings.po

.kodi/addons/plugin.video.bitchute/resources/language/Hebrew:
.           ..          strings.po
```

I've set my username and password in the plugin's settings.  I just logged into BitChute on my computer to make sure the account still worked.  It still won't log in, though, and produces the same error as above.
